function [SensorConnectivityGraph ,GatewaySensors] = GenerateConnectivityMatrix(fieldSize)
addpath('./RoutingUtility'); 
% required config
SensorDist                    = 0.5;
FieldSizeFactorX              = fieldSize; % bug - doens't work for numbers smaller than 14 
FieldSizeFactorY              = fieldSize; 
FieldSize                     = [FieldSizeFactorX*SensorDist, FieldSizeFactorY*SensorDist];
LocationNoise                 = SensorDist*0.7;
AtomGridSizeX                 = SensorDist*6;
AtomGridSizeY                 = SensorDist*6;
GatewayAtomDepth              = SensorDist*6;
MeanSensorConnections         = 9;
ConnectionSearchRadiusInAtoms = 1;
ChannelGradeTh                = 2; 
ChannelGradeFunc              = @(Xa, Ya, Xb, Yb) abs(Xb-Xa).^2 + abs(Yb-Ya).^2;
GatewayAtomsX                 = 2;
GatewayAtomsY                 = 1:2;


% Generate Field Scenario
[SensorPosX, SensorPosY] = GenerateFieldScenario(...
    SensorDist,...
    FieldSize,...
    LocationNoise...
    );
numOfSensors =  numel(SensorPosX);

% Sort into Atoms
[SensorAtomIndex, AtomGridLenX, AtomGridLenY] = GetAtomIndices(...
    SensorPosX,...
    SensorPosY,...
    AtomGridSizeX,...
    AtomGridSizeY,...
    GatewayAtomDepth...
    );

% Generate Sensor Connectivity Graph
SensorConnectivityGraph = GetConnectivityGraph(...
    numOfSensors,...
    MeanSensorConnections,...
    AtomGridLenX,...
    AtomGridLenY,...
    ConnectionSearchRadiusInAtoms,...
    SensorAtomIndex,...
    SensorPosX,...
    SensorPosY,...
    ChannelGradeFunc,...
    ChannelGradeTh...
    );

% Find gateway neighbours
GatewaySensors = FindGWAtoms(...
                             GatewayAtomsX,...
                             GatewayAtomsY,...
                             AtomGridLenX,...
                             AtomGridLenY,...
                             SensorAtomIndex...
                             );
end

